### ISSUE TITLE
When will this repository support MUSES?

### ISSUE THREAD

**Issue by czhaneva** [xlliu7/MUSES#12]
Thanks for your awesome work!
I'd like to know when will this repository support MUSES. Or train the model in an end-to-end manner (including I3D backbone!)
Thanks again~

**Comment by xlliu7** [comment]
Hi, the repository supports MUSES now. Sorry for the delay. If you're interested in end-to-end training, you can stay tuned for our CVPR'22 work about end-to-end training. Close the issue now. Feel free to re-open it if you come across any problem.
