### ISSUE TITLE
Error on running eval.py

### ISSUE THREAD

**Issue by doltonfernandes** [xlliu7/MUSES#8]
Exact command used:
`python eval.py thumos14 outputs/scores/thumos14_flow -j8 --cfg data/cfgs/thumos14_flow.yml --nms_threshold 0.4|tee -a outputs/eval.log`

![image](https://user-images.githubusercontent.com/42113482/122722225-12a6a700-d28f-11eb-9c92-aec9c257a413.png)

**Comment by xlliu7** [comment]
Thanks.  I have fixed it.
